### ISSUE TITLE
Update Notification using GitHub API

### ISSUE THREAD

**Issue by bux** [bux/tabler#38]

**Comment by bux578** [comment]
My toy-around-with-this-shit class:
https://github.com/bux578/tabler/blob/githubGetVersion/tabler/Helper/GitHubHelper.cs

`private const string RELEASE_URL = "https://api.github.com/repos/bux578/tabler/releases";`

**Comment by bux** [comment]
fixed in 1cb896cef00e9b81038f4ff6801ad561c541ec7e
