### ISSUE TITLE
tabler takes long to save big files

### ISSUE THREAD

**Issue by GodofMonkeys** [bux/tabler#42]
Hi bux578, I am a translator for ArmA3 main game into chinese.
I use tool include your tabler to help me proofread offical stringtable.xml text.
I have some idea, hope you can use these idea to help this utilitie tool more complete.

---

offical stringtable.xml always some big (e.g. 400kb~700kb, or more to 2.92Mb). 
   When tabler open larger file, It will run slow, and save file also slow.

   When file big more than 1.99Mb to above 2Mb, the tabler will not respond at saving. Also, when save on about 1.5Mb file, it will take about 5min to saved file. Can fix this problem?

---

Once again thank you for making this tool :D

**Comment by bux578** [comment]
#45
