### ISSUE TITLE
Open a new file more than once ?

### ISSUE THREAD

**Issue by 11RDP-LoupVert** [bux/tabler#47]
Hello,
would it be possible to open a new file more than once?

So far I have to close the tool if I want to open another (set of) language file(s).

Still a great tool though.

**Comment by bux** [comment]
Could you explain in a bit more detail what you're trying to achieve?

**Comment by 11RDP-LoupVert** [comment]
As I work on several mod/missions, when I've opened language file(s), I would like to open other files, from another Mod/Mission.

As for now, I have to exit Tabler and open it again to be able to do so.

**Comment by bux** [comment]
Ah, ok. I will look into it.

**Comment by bux** [comment]
@11RDP-LoupVert Could you try it with the new version?
merci!

**Comment by 11RDP-LoupVert** [comment]
Sure! Could you please compile an exe or guide me through?
