### ISSUE TITLE
Use SaveFileDialog class, to create an easier navigation experience

### ISSUE THREAD

**Issue by CreepPork** [bux/tabler#51]
The current implementation works fine, but the biggest gripe I have with it is that it uses the old way of opening files.
This is incredibly frustrating if you have to navigate to a folder that is buried in the drive.

Using the [SaveFileDialog](https://msdn.microsoft.com/en-us/library/system.windows.forms.savefiledialog(v=vs.110).aspx) class is a much better way to display files and folders to end user as it supports quick navigation such as bookmarks.

**Comment by bux** [comment]
I'm already using that: https://github.com/bux/tabler/blob/master/tabler/Forms/GridUI.cs#L61

Maybe you mean something like that: https://stackoverflow.com/a/23024435 ?

**Comment by CreepPork** [comment]
Yes, my mistake. I had one project where I used the SaveFileDialog and I want to attach a photo but sadly I cannot find the project, but that class should be the correct one.
