### ISSUE TITLE
Files are saved with BOM when source is without

### ISSUE THREAD

**Issue by veteran29** [bux/tabler#52]
When Tabler is used to edit files encoded in utf-8 without BOM character they will be saved back in utf-8 with BOM.

I think it would be reasonable to leave files original encoding when saving them.

**Comment by dedmen** [comment]
https://social.msdn.microsoft.com/Forums/en-US/9b8d1603-3e76-4b09-b9a8-e529d93f9e0a/how-to-suppress-the-bom-while-using-xmltextwriter?forum=xmlandnetfx

**Comment by bux** [comment]
Closed in c67fd0dc69655878d30be6c0002f7ebdde928a82
