### ISSUE TITLE
Better feedback when saving

### ISSUE THREAD

**Issue by RevoArma3** [bux/tabler#60]
Saving of larger files takes quite a few seconds. During that time the user recieves no feedback whether or not the saving is still ongoing. When saving has finished only a small message is shown at the bottom. When the user wants to exit the application one is asked whether one wants to drop all changes.

Suggestions:
- While saving, a progressbar should be shown.
- When the user exits one minute after saving, no prompt is shown, it just closes.
- When the user wants to exit the programm without saving before, a prompt opens: Save, Cancel, Exit without Saving

**Comment by bux** [comment]
Done in a77a5bfb3aff90ee6fa2df81d8cc145d7e6121a2
