### ISSUE TITLE
Add ability of changing the font

### ISSUE THREAD

**Issue by classicarma** [bux/tabler#69]
The default font is ugly for me.
![](https://i.imgur.com/hJAjTPS.jpg)

**Comment by bux** [comment]
@classicarma What default Windows font would be better to display japanese characters?

**Comment by classicarma** [comment]
I guess Segoe UI or MS gothic (only have Japanese Windows) is better font for Japanese characters. I just want to more visibility for editing table in the tabler, because the default font is too small.
If it's difficult to add font changes, What about add increase/decrease font size option?

**Comment by barman75** [comment]
Yes, please consider to add font settings. It would be very useful for those who have high resolution disaplays.
Thank you!
